package util;

public enum CategoriaDeProduto {

	MERCEARIADEALTOGIRO, MERCEARIADOCE, MATINAIS, PERECIVEISCONGELADOSERESFRIADOS,
	PERECIVEISLACTEOS, BEBIDASNAOALCOOLICAS, BEBIDASALCOOLICAS, HIGIENESAUDEEBELEZA,
	LIMPEZA, DESCARTAVEIS, BAZAR, EQUIPAMENTOSINSUMOSESERVIÇOS;
	
}
