package util;

public enum CategoriaDeProduto {

	MERCEARIADEALTOGIRO, MERCEARIADOCE, MATINAIS, PERECIVEIS_CONGELADOS_E_RESFRIADOS,
	PERECIVEIS_LACTEOS, BEBIDAS_NAO_ALCOOLICAS, BEBIDAS_ALCOOLICAS, HIGIENE_SAUDE_E_BELEZA,
	LIMPEZA, DESCARTAVEIS, BAZAR, EQUIPAMENTOS_INSUMOS_E_SERVICOS;
	
}
